# Generated by Django 4.2.6 on 2023-10-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("desc", models.TextField()),
                ("category", models.TextField()),
                ("logo_url", models.ImageField(upload_to="pics")),
            ],
        ),
    ]
